# vtidal, rpm, ratioie, fio2, pmax, flujoaire, peep
resp_params:
  tvm:        #volumen tidal
    screen_name: Vol. Tidal
    units:  mL
    min: 100      # ml
    max: 1000     # ml
    default: 200
    step: 10
    format: .0f
  brpm:  #Respiraciones por minuto
    screen_name: Resp. por min
    units: ""
    min: 5
    max: 100
    default: 20
    step: 1
    format: .0f
  ier:
    screen_name: "Ratio I:E"
    units: ""
    # If options is present, use values as index
    options: !!python/tuple ['3.0:1', '2.8:1', '2.6:1', '2.4:1', '2.2:1', '2:1', '1.8:1', '1.6:1', '1.4:1', '1.2:1', '1:1', '1:1.2', '1:1.4', '1:1.6', '1:1.8', '1:2.0', '1:2.2', '1:2.4', '1:2.6', '1:2.8', '1:3.0', '1:3.2', '1:3.4', '1:3.6', '1:3.8', '1:4.0', '1:4.2', '1:4.4', '1:4.6', '1:4.8', '1:5.0']
    min: 0
    max: 30
    default: 10
    step: 1
    format: s
  fio2:
    screen_name: FiO2
    units: "%"
    min: 21
    max: 100
    default: 21
    step: 1
    format: .0f
  peep:
    screen_name: PEEP
    units: cm H2O
    min: 5 #cm H2O
    max: 15
    default: 5
    step: 1
    format: .0f
  tf:
    screen_name: Flujo total
    units: L/min
    min: 1
    max: 10
    default: 5
    step: 0.5
    format: .1f
gscale: # Escala de tiempo de los graficos
  options: [5, 20, 60]
modes:
  vcv:
    vtidal:
      adjustable: True
      default:
    rpm:
      adjustable: True
      default: 15 # Respiraciones por minuto
    ratioie:
      adjustable: True
      default: 2  #1:x relación tiempo-inspiratorio : tiempo-exalatorio
    fio2:
      adjustable: True
      default: 100 # porcentaje de oxigeno
    pmax:
      adjustable: False
      default:
    flujoaire:
      adjustable: True
      default: 50 #litros por minuto
    peep:
      adjustable: True
      default: 7 #cmH2O
  pcv:
    vtidal:
      adjustable: True
      default:
    rpm:
      adjustable: True
      default: 15 # Respiraciones por minuto
    ratioie:
      adjustable: True
      default: 2  #1:x relación tiempo-inspiratorio : tiempo-exalatorio
    fio2:
      adjustable: True
      default: 100 # porcentaje de oxigeno
    pmax:
      adjustable: False
      default:
    flujoaire:
      adjustable: True
      default: 50 #litros por minuto
    peep:
      adjustable: True
      default: 7 #cmH2O
logging:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    root_handler:
      class: logging.NullHandler
    my_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: logs/respiface.log
      when: midnight
      interval: 1
      backupCount: 7
      encoding: utf-8
  loggers:
    gui:
      handlers: [my_handler]
  root:
    level: DEBUG
    handlers: [root_handler]