# vtidal, rpm, ratioie, fio2, pmax, flujoaire, peep
resp_params:
  tvm:        #volumen tidal
    screen_name: Vol. Tidal
    units:  mL
    min: 100      # ml
    max: 1000     # ml
    default: 200
    step: 10
    format: .0f
    measured: True
  brpm:  #Respiraciones por minuto
    screen_name: Resp. por min
    units: ""
    min: 5
    max: 100
    default: 20
    step: 1
    format: .0f
    measured: False
  ier_i:
    screen_name: "Ratio I:E"
    units: ""
    min: 1
    max: 3
    default: 1
    step: 1
    format: .0f
    measured: False
  ier_e:
    screen_name: "Ratio I:E"
    units: ""
    min: 1
    max: 5
    default: 3
    step: 1
    format: .0f
    measured: False
  fio2:
    screen_name: FiO2
    units: "%"
    min: 21
    max: 100
    default: 21
    step: 1
    format: .0f
    measured: True
  peep:
    screen_name: PEEP
    units: <html>cm H<span style=" vertical-align:sub;">2</span>O</html>
    min: 0 #cm H2O
    max: 15
    default: 5
    step: 1
    format: .0f
    measured: True
  mf:
    screen_name: Flujo
    units: L/min
    min: 1
    max: 40
    default: 5
    step: 0.5
    format: .1f
    measured: True
  mp:
    screen_name: P max
    units: <html>cm H<span style=" vertical-align:sub;">2</span>O</html>
    min: 1
    max: 55
    default: 10
    step: 1
    format: .0f
    measured: True
gscale: # Escala de tiempo de los graficos
  options: [5, 20, 60]
modes:
  vcv:
    tvm:
      adjustable: True
      default: 200
    brpm:
      adjustable: True
      default: 15 # Respiraciones por minuto
    ier_i:
      adjustable: True
      default: 1
    ier_e:
      adjustable: True
      default: 3
    fio2:
      adjustable: True
      default: 100 # porcentaje de oxigeno
    peep:
      adjustable: True
      default: 5
    mf:
      adjustable: True
      default: 50 # litros por minuto
    mp:
      adjustable: False
      default: 7 #cmH2O
  pcv:
    tvm:
      adjustable: False
      default: 200
    brpm:
      adjustable: True
      default: 15 # Respiraciones por minuto
    ier_i:
      adjustable: True
      default: 1
    ier_e:
      adjustable: True
      default: 3
    fio2:
      adjustable: True
      default: 100 # porcentaje de oxigeno
    peep:
      adjustable: True
      default: 5
    mf:
      adjustable: True
      default: 50 # litros por minuto
    mp:
      adjustable: True
      default: 7 #cmH2O
logging:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    root_handler:
      class: logging.NullHandler
    my_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: logs/respiface.log
      when: midnight
      interval: 1
      backupCount: 7
      encoding: utf-8
  loggers:
    gui:
      handlers: [my_handler]
  root:
    level: DEBUG
    handlers: [root_handler]