# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Chile))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 480))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frm_pmax = QtWidgets.QFrame(self.centralwidget)
        self.frm_pmax.setFrameShape(QtWidgets.QFrame.Panel)
        self.frm_pmax.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_pmax.setLineWidth(1)
        self.frm_pmax.setObjectName("frm_pmax")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frm_pmax)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frm_pmax)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lbl_pmax = QtWidgets.QLabel(self.frm_pmax)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pmax.sizePolicy().hasHeightForWidth())
        self.lbl_pmax.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pmax.setFont(font)
        self.lbl_pmax.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pmax.setObjectName("lbl_pmax")
        self.verticalLayout_2.addWidget(self.lbl_pmax)
        self.label_2 = QtWidgets.QLabel(self.frm_pmax)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.frm_pmax)
        self.frm_pmedia = QtWidgets.QFrame(self.centralwidget)
        self.frm_pmedia.setFrameShape(QtWidgets.QFrame.Panel)
        self.frm_pmedia.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_pmedia.setLineWidth(1)
        self.frm_pmedia.setObjectName("frm_pmedia")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frm_pmedia)
        self.verticalLayout_11.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.frm_pmedia)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.lbl_pmedia = QtWidgets.QLabel(self.frm_pmedia)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pmedia.sizePolicy().hasHeightForWidth())
        self.lbl_pmedia.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pmedia.setFont(font)
        self.lbl_pmedia.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pmedia.setObjectName("lbl_pmedia")
        self.verticalLayout_11.addWidget(self.lbl_pmedia)
        self.label_4 = QtWidgets.QLabel(self.frm_pmedia)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.horizontalLayout.addWidget(self.frm_pmedia)
        self.frm_peep = QtWidgets.QFrame(self.centralwidget)
        self.frm_peep.setFrameShape(QtWidgets.QFrame.Panel)
        self.frm_peep.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_peep.setLineWidth(2)
        self.frm_peep.setObjectName("frm_peep")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frm_peep)
        self.verticalLayout_10.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frm_peep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.lbl_peep = QtWidgets.QLabel(self.frm_peep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_peep.sizePolicy().hasHeightForWidth())
        self.lbl_peep.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_peep.setFont(font)
        self.lbl_peep.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_peep.setObjectName("lbl_peep")
        self.verticalLayout_10.addWidget(self.lbl_peep)
        self.label_6 = QtWidgets.QLabel(self.frm_peep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.horizontalLayout.addWidget(self.frm_peep)
        self.frm_ratioie = QtWidgets.QFrame(self.centralwidget)
        self.frm_ratioie.setFrameShape(QtWidgets.QFrame.Panel)
        self.frm_ratioie.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_ratioie.setLineWidth(2)
        self.frm_ratioie.setObjectName("frm_ratioie")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_ratioie)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frm_ratioie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lbl_ier = QtWidgets.QLabel(self.frm_ratioie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ier.sizePolicy().hasHeightForWidth())
        self.lbl_ier.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ier.setFont(font)
        self.lbl_ier.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ier.setObjectName("lbl_ier")
        self.verticalLayout_3.addWidget(self.lbl_ier)
        self.label_21 = QtWidgets.QLabel(self.frm_ratioie)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.horizontalLayout.addWidget(self.frm_ratioie)
        self.frm_rpm = QtWidgets.QFrame(self.centralwidget)
        self.frm_rpm.setFrameShape(QtWidgets.QFrame.Panel)
        self.frm_rpm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_rpm.setLineWidth(2)
        self.frm_rpm.setObjectName("frm_rpm")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frm_rpm)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.frm_rpm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.lbl_brpm = QtWidgets.QLabel(self.frm_rpm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_brpm.sizePolicy().hasHeightForWidth())
        self.lbl_brpm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_brpm.setFont(font)
        self.lbl_brpm.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_brpm.setObjectName("lbl_brpm")
        self.verticalLayout_4.addWidget(self.lbl_brpm)
        self.label_23 = QtWidgets.QLabel(self.frm_rpm)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.horizontalLayout.addWidget(self.frm_rpm)
        self.frm_vtidal = QtWidgets.QFrame(self.centralwidget)
        self.frm_vtidal.setFrameShape(QtWidgets.QFrame.Panel)
        self.frm_vtidal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_vtidal.setLineWidth(2)
        self.frm_vtidal.setObjectName("frm_vtidal")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frm_vtidal)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.frm_vtidal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.lbl_tvm = QtWidgets.QLabel(self.frm_vtidal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_tvm.sizePolicy().hasHeightForWidth())
        self.lbl_tvm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tvm.setFont(font)
        self.lbl_tvm.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tvm.setObjectName("lbl_tvm")
        self.verticalLayout_5.addWidget(self.lbl_tvm)
        self.label_12 = QtWidgets.QLabel(self.frm_vtidal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout.addWidget(self.frm_vtidal)
        self.frm_flujototal = QtWidgets.QFrame(self.centralwidget)
        self.frm_flujototal.setFrameShape(QtWidgets.QFrame.Panel)
        self.frm_flujototal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_flujototal.setLineWidth(2)
        self.frm_flujototal.setObjectName("frm_flujototal")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frm_flujototal)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.frm_flujototal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.lbl_flujoaire = QtWidgets.QLabel(self.frm_flujototal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_flujoaire.sizePolicy().hasHeightForWidth())
        self.lbl_flujoaire.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_flujoaire.setFont(font)
        self.lbl_flujoaire.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_flujoaire.setObjectName("lbl_flujoaire")
        self.verticalLayout_6.addWidget(self.lbl_flujoaire)
        self.label_14 = QtWidgets.QLabel(self.frm_flujototal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalLayout.addWidget(self.frm_flujototal)
        self.frm_fio2 = QtWidgets.QFrame(self.centralwidget)
        self.frm_fio2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frm_fio2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_fio2.setLineWidth(2)
        self.frm_fio2.setObjectName("frm_fio2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frm_fio2)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.frm_fio2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.lbl_fio2 = QtWidgets.QLabel(self.frm_fio2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_fio2.sizePolicy().hasHeightForWidth())
        self.lbl_fio2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fio2.setFont(font)
        self.lbl_fio2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fio2.setObjectName("lbl_fio2")
        self.verticalLayout_7.addWidget(self.lbl_fio2)
        self.label_16 = QtWidgets.QLabel(self.frm_fio2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.horizontalLayout.addWidget(self.frm_fio2)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.layout_flow = QtWidgets.QHBoxLayout()
        self.layout_flow.setObjectName("layout_flow")
        self.f_widget = LayoutWidget(self.centralwidget)
        self.f_widget.setObjectName("f_widget")
        self.layout_flow.addWidget(self.f_widget)
        self.gridLayout.addLayout(self.layout_flow, 1, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_13.addWidget(self.label_24)
        self.gridLayout.addLayout(self.verticalLayout_13, 1, 2, 1, 1)
        self.layout_pressure = QtWidgets.QHBoxLayout()
        self.layout_pressure.setObjectName("layout_pressure")
        self.p_widget = LayoutWidget(self.centralwidget)
        self.p_widget.setObjectName("p_widget")
        self.layout_pressure.addWidget(self.p_widget)
        self.gridLayout.addLayout(self.layout_pressure, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_12.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.gridLayout.addLayout(self.verticalLayout, 0, 3, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 3, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frm_gscale = QtWidgets.QFrame(self.centralwidget)
        self.frm_gscale.setMinimumSize(QtCore.QSize(135, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frm_gscale.setFont(font)
        self.frm_gscale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_gscale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_gscale.setObjectName("frm_gscale")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frm_gscale)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_19 = QtWidgets.QLabel(self.frm_gscale)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.lbl_gscale = QtWidgets.QLabel(self.frm_gscale)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_gscale.setFont(font)
        self.lbl_gscale.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_gscale.setObjectName("lbl_gscale")
        self.horizontalLayout_4.addWidget(self.lbl_gscale)
        self.horizontalLayout_2.addWidget(self.frm_gscale)
        self.frm_op_mode = QtWidgets.QFrame(self.centralwidget)
        self.frm_op_mode.setMinimumSize(QtCore.QSize(20, 0))
        self.frm_op_mode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_op_mode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_op_mode.setObjectName("frm_op_mode")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frm_op_mode)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_20 = QtWidgets.QLabel(self.frm_op_mode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.lbl_op_mode = QtWidgets.QLabel(self.frm_op_mode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_op_mode.sizePolicy().hasHeightForWidth())
        self.lbl_op_mode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_op_mode.setFont(font)
        self.lbl_op_mode.setObjectName("lbl_op_mode")
        self.horizontalLayout_3.addWidget(self.lbl_op_mode)
        self.horizontalLayout_2.addWidget(self.frm_op_mode)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btnConfig = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConfig.sizePolicy().hasHeightForWidth())
        self.btnConfig.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnConfig.setFont(font)
        self.btnConfig.setObjectName("btnConfig")
        self.horizontalLayout_2.addWidget(self.btnConfig)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "P max"))
        self.lbl_pmax.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">cm H<span style=\" vertical-align:sub;\">2</span>O</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "P media"))
        self.lbl_pmedia.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">cm H<span style=\" vertical-align:sub;\">2</span>O</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "PEEP"))
        self.lbl_peep.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">cm H<span style=\" vertical-align:sub;\">2</span>O [5.0]</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Ratio I:E"))
        self.lbl_ier.setText(_translate("MainWindow", "0:0"))
        self.label_9.setText(_translate("MainWindow", "Resp/min"))
        self.lbl_brpm.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "V Tidal"))
        self.lbl_tvm.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ml [500]</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Flujo Total"))
        self.lbl_flujoaire.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">L/min [25.0]</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>FiO<span style=\" vertical-align:sub;\">2</span></p></body></html>"))
        self.lbl_fio2.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">% [50.0]</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Alerta 1"))
        self.label_24.setText(_translate("MainWindow", "Alerta 2"))
        self.label_17.setText(_translate("MainWindow", "Alerta 1"))
        self.label_18.setText(_translate("MainWindow", "Alerta 2"))
        self.pushButton.setText(_translate("MainWindow", "Alarma"))
        self.label_8.setText(_translate("MainWindow", "1 m"))
        self.pushButton_3.setText(_translate("MainWindow", "Alarma"))
        self.label_10.setText(_translate("MainWindow", "10 m"))
        self.label_19.setText(_translate("MainWindow", "Escala:"))
        self.lbl_gscale.setText(_translate("MainWindow", "60 s"))
        self.label_20.setText(_translate("MainWindow", "Modo: "))
        self.lbl_op_mode.setText(_translate("MainWindow", "VCV"))
        self.pushButton_2.setText(_translate("MainWindow", "Pant. bloq."))
        self.btnConfig.setText(_translate("MainWindow", "CONFIGURAR"))
from pyqtgraph import LayoutWidget
